name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      matrix:
        rust-version:
          - "stable"
          - "beta"
          - "nightly"
          - "1.44"
        api-version:
          - "v4_3"
          - "v4_4"

    runs-on: ubuntu-18.04

    steps:

      - uses: actions/checkout@v2

      - name: Install Rust ${{ matrix.rust-version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --features ${{ matrix.api-version }}

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features ${{ matrix.api-version }}
